# Generated by Django 4.2 on 2024-01-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_reservation_reservation_date_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.CharField(max_length=100),
        ),
    ]
