# Generated by Django 4.2 on 2024-01-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_reservation_price_reservation_price_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='total',
            new_name='change',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='total_currency',
            new_name='change_currency',
        ),
    ]
