# Generated by Django 4.2 on 2024-01-07 15:52

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_rename_total_reservation_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='book_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('500000.0'), default_currency='PHP', max_digits=12),
        ),
    ]
