# Generated by Django 4.2 on 2024-01-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_room_book_count_alter_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='book_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
