# Generated by Django 4.2 on 2024-01-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_room_book_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guest',
            field=models.BooleanField(default=False),
        ),
    ]
